proxy:
  container_name: proxy
  restart: always
  image: accenture/adop-nginx:me
  net: adop
  ports:
    - "80:80"
    - "443:443"
  environment:
    - "LDAP_SERVER=${LDAP_SERVER}"
    - "LDAP_USERNAME=${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
    - "LDAP_PASSWORD=${LDAP_PWD}"
    - "LDAP_USER_BASE_DN=${LDAP_USER_BASE_DN},${LDAP_FULL_DOMAIN}"
    - "LDAP_GROUP_ATTRIBUTE=member"
    - "LDAP_USER_ID_ATTRIBUTE=cn"
    - "LDAP_USER_OBJECT_CLASS=inetOrgPerson"

ldap:
  container_name: ldap
  net: adop
  restart: always
  image: accenture/adop-ldap:me
  ports:
    - "389:389/tcp"
  environment:
    INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
    INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
    JENKINS_PLATFORM_USERNAME: ${JENKINS_PLATFORM_USERNAME}
    JENKINS_PASSWORD: ${JENKINS_PWD}
    SLAPD_PASSWORD: ${LDAP_PWD}
    SLAPD_DOMAIN: ${LDAP_DOMAIN}
    SLAPD_FULL_DOMAIN: ${LDAP_FULL_DOMAIN}

sensu-uchiwa:
  net: adop
  container_name: sensu-uchiwa
  restart: always
  image: sstarcher/uchiwa:0.15.0
  environment:
    SENSU_HOSTNAME: sensu-api
    SENSU_DC_NAME: Sensu
  expose:
    - "3000"

sensu-api:
  net: adop
  container_name: sensu-api
  restart: always
  image: accenture/adop-sensu:me
  command: api
  expose:
    - "4567"
  environment:
    TRANSPORT_NAME: rabbitmq
    RABBITMQ_HOST: sensu-rabbitmq
    REDIS_HOST: sensu-redis

sensu-server:
  net: adop
  container_name: sensu-server
  restart: always
  image: accenture/adop-sensu:me
  command: server
  environment:
    API_HOST: sensu-api
    RABBITMQ_HOST: sensu-rabbitmq
    REDIS_HOST: sensu-redis
    TRANSPORT_NAME: rabbitmq

sensu-client:
  net: adop
  container_name: sensu-client
  restart: always
  image: accenture/adop-sensu:me
  command: client
  environment:
    TRANSPORT_NAME: rabbitmq
    CLIENT_NAME: core
    CLIENT_ADDRESS: 127.0.0.1
    RABBITMQ_HOST: sensu-rabbitmq
    JENKINS_PREFIX: jenkins
    CLIENT_SUBSCRIPTIONS: "proxy,jenkins,nexus,sonarqube,sensu,kibana"

sensu-rabbitmq:
  net: adop
  container_name: sensu-rabbitmq
  restart: always
  image: rabbitmq:3.5.7-management
  expose:
    - "5672"
    - "5671"
    - "15672"
    - "15671"

sensu-redis:
  net: adop
  container_name: sensu-redis
  restart: always
  image: redis:3.0.7
  expose:
    - "6379"

sonar-mysql:
  net: adop
  container_name: sonar-mysql
  restart: always
  image: mysql:5.6.25
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: ${PASSWORD_SQL}
    MYSQL_USER: ${SONAR_MYSQL_USER}
    MYSQL_PASSWORD: ${SONAR_MYSQL_PASSWORD}
    MYSQL_DATABASE: ${SONAR_MYSQL_DATABASE}

sonar:
  net: adop
  container_name: sonar
  restart: always
  image: accenture/adop-sonar:0.4.1
  expose:
    - "9000"
  environment:
    - "SONARQUBE_JDBC_USERNAME=${SONAR_MYSQL_USER}"
    - "SONARQUBE_JDBC_PASSWORD=${SONAR_MYSQL_PASSWORD}"
    - "LDAP_URL=ldap://${LDAP_SERVER}"
    - "LDAP_BIND_DN=${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
    - "LDAP_BIND_PASSWORD=${LDAP_PWD}"
    - "LDAP_USER_BASE_DN=${LDAP_USER_BASE_DN},${LDAP_FULL_DOMAIN}"
    - "LDAP_USER_REQUEST=(&(objectClass=inetOrgPerson)(uid={login}))"
    - "LDAP_USER_REAL_NAME_ATTRIBUTE=displayName"
    - "LDAP_USER_EMAIL_ATTRIBUTE=mail"
    - "LDAP_GROUP_BASE_DN=${LDAP_GROUP_BASE_DN},${LDAP_FULL_DOMAIN}"
    - "LDAP_GROUP_REQUEST=(&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))"
    - "LDAP_GROUP_ID_ATTRIBUTE=cn"
    - "SONARQUBE_JDBC_URL=jdbc:mysql://sonar-mysql:3306/${SONAR_MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"

jenkins:
  net: adop
  container_name: jenkins
  restart: always
  image: accenture/adop-jenkins:0.3.3
  ports:
    - "50000:50000/tcp"
  expose:
    - "8080"
    - "50000"
  privileged: true
  environment:
    JENKINS_OPTS: "--prefix=/jenkins"
    ROOT_URL: "${PROTO}://${TARGET_HOST}/jenkins/"
    LDAP_SERVER: "${LDAP_SERVER}"
    LDAP_ROOTDN: "${LDAP_FULL_DOMAIN}"
    LDAP_USER_SEARCH_BASE: "${LDAP_USER_BASE_DN}"
    LDAP_USER_SEARCH: "${LDAP_USER_SEARCH}"
    LDAP_GROUP_SEARCH_BASE: "${LDAP_GROUP_BASE_DN}"
    LDAP_GROUP_SEARCH_FILTER: ""
    LDAP_GROUP_MEMBERSHIP_FILTER: ""
    LDAP_MANAGER_DN: "${LDAP_MANAGER_DN}"
    LDAP_MANAGER_PASSWORD: ${LDAP_PWD}
    LDAP_INHIBIT_INFER_ROOTDN: "false"
    LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: "false"
    LDAP_DISPLAY_NAME_ATTRIBUTE_NAME: "displayName"
    LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME: "mail"
    LDAP_GROUP_NAME_ADMIN: "${LDAP_GROUP_NAME_ADMIN}"
    INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
    INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD_PLAIN}
    SONAR_SERVER_URL: "http://sonar:9000/sonar/"
    SONAR_ACCOUNT_LOGIN: ${SONAR_ACCOUNT_LOGIN}
    SONAR_ACCOUNT_PASSWORD: ${PASSWORD_JENKINS}
    SONAR_DB_URL: "jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&amp;characterEncoding=utf8"
    SONAR_DB_LOGIN: ${SONAR_DB_LOGIN}
    SONAR_DB_PASSWORD: ${SONAR_DB_PASSWORD}
    SONAR_PLUGIN_VERSION: ""
    SONAR_ADDITIONAL_PROPS: ""
    SONAR_RUNNER_VERSION: "2.9.0.670"
    ANT_VERSION: "1.9.4"
    MAVEN_VERSION: "3.0.5"
    NODEJS_VERSION: "6.9.4"
    NODEJS_GLOBAL_PACKAGES: "grunt-cli@~0.1.13 bower@~1.3.12 plato@~1.2.1"
    NODEJS_PACKAGES_REFRESH_HOURS: "72"
    GIT_GLOBAL_CONFIG_NAME: "ADOP Jenkins"
    GROOVY_VERSION: "2.4.8"
    GIT_GLOBAL_CONFIG_EMAIL: "jenkins@${LDAP_DOMAIN}"
    DOCKER_HOST: ${DOCKER_HOST}
    CARTRIDGE_SOURCES: ${CARTRIDGE_SOURCES}
    ADOP_GERRIT_ENABLED: "false"
    ADOP_PLATFORM_MANAGEMENT_VERSION: "1c2aac27a926796490cf5a1b97f7064af31c44fe"

jenkins-slave:
  net: adop
  container_name: jenkins-slave
  restart: always
  image: accenture/adop-jenkins-slave:0.1.4
  privileged: true
  environment:
    SLAVE_LABELS: "aws ldap java8 docker"
    SWARM_PASSWORD: ${PASSWORD_JENKINS}
    SLAVE_EXECUTORS: ${SLAVE_EXECUTORS}
    INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
    INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD_PLAIN}

nexus:
  net: adop
  container_name: nexus
  restart: always
  image:  accenture/adop-nexus:0.2.2
  expose:
    - "8081"
  environment:
    NEXUS_BASE_URL: "${PROTO}://${TARGET_HOST}/nexus"
    NEXUS_CONTEXT: "nexus"
    NEXUS_ADMIN_PASSWORD: "${INITIAL_ADMIN_PASSWORD_PLAIN}"
    LDAP_SEARCH_BASE: "${LDAP_FULL_DOMAIN}"
    LDAP_ENABLED: "true"
    LDAP_URL: "ldap"
    LDAP_BIND_DN: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
    LDAP_BIND_PASSWORD: "${LDAP_PWD}"
    LDAP_USER_PASSWORD_ATTRIBUTE: "userPassword"
    LDAP_USER_BASE_DN: "${LDAP_USER_BASE_DN}"
    LDAP_GROUP_BASE_DN: "${LDAP_GROUP_BASE_DN}"

ldap-ltb:
  net: adop
  container_name: ldap-ltb
  restart: always
  image: accenture/adop-ldap-ltb:0.1.0
  expose:
    - "80"
  environment:
    LDAP_LTB_URL: "ldap://${LDAP_SERVER}"
    LDAP_LTB_DN: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
    LDAP_LTB_PWD: "${LDAP_PWD}"
    LDAP_LTB_BS: "${LDAP_FULL_DOMAIN}"

ldap-phpadmin:
  net: adop
  container_name: ldap-phpadmin
  restart: always
  image: accenture/adop-ldap-phpadmin:0.1.0
  expose:
    - "80"
  environment:
    LDAP_SERVER_NAME: "LDAP"
    LDAP_SERVER_HOST: "ldap"
    LDAP_SERVER_PORT: "389"
    LDAP_SERVER_BIND_ID: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
    LDAP_SERVER_BASE_DN: "${LDAP_FULL_DOMAIN}"


elasticsearch:
  net: adop
  container_name: elasticsearch
  restart: always
  image: elasticsearch:2.1.1
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
  volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data

logstash:
  net: adop
  container_name: logstash
  restart: always
  image: accenture/adop-logstash:0.1.0
  environment:
    - LS_HEAP_SIZE=1024m
  ports:
    - "12201:12201/udp"
    - "25826:25826/udp"
    - "5000:5000/tcp"

kibana:
  net: adop
  container_name: kibana
  restart: always
  image: kibana:4.3.1
  command: kibana
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
    - "5601:5601"
